services:
  db:
    image: postgres:16-alpine
    container_name: oshime_local_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: oshime_development
    ports:
      - "54322:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
